// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function querySelectorAll(query) {
  return Array.from(document.querySelectorAll(query));
}

exports.querySelectorAll = querySelectorAll;
/* No side effect */
